### ISSUE TITLE
Unable to find check run for action: rkusajest-actionlatest

### ISSUE THREAD

**Issue by artalat** [rkusa/jest-action#2]
Hi, thank you for this action. I'm trying to integrate it but getting this error: 

```
Unable to find check run for action: rkusajest-actionlatest
````

Anything I'm doing wrong? Thanks

**Comment by rkusa** [comment]
Sorry for the late response, I accidentally disabled notifications for this repo. Since this action does not work with the release version of Github actions anymore, I am going to archive it. This action was using the `GITHUB_ACTION` env to retrieve the check the action was executed in. However this value is now set to other things, like `run1`, `self`, or `rkusajest-actionlatest` and can thus not been used for this purpose anymore (and there is no alternative).

I guess the recommended alternative are [Problem Matchers](https://github.com/actions/toolkit/blob/master/docs/commands.md#problem-matchers) now. Here is an example problem matcher for eslint: https://github.com/actions/setup-node/blob/master/.github/eslint-compact.json
